=== k4iru/School/HTTP-5203/assignment-2/xml/tickets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tickets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ticketId" type="xs:integer" />
                            <xs:element name="dateOfIssue" type="xs:dateTime" />
                            <xs:element name="status" type="xs:string" />
                            <xs:element name="userId" type="xs:integer" />
                            <xs:element name="subject" type="xs:string" />
                            <xs:element name="description" type="xs:string" />
                            <xs:element name="supportMessages" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="message" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="userIdComment" type="xs:integer" />
                                                    <xs:element name="content" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="time" type="xs:dateTime" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== k4iru/School/HTTP-5203/assignment-2/xml/tickets.xml
<?xml version="1.0" encoding="UTF-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets.xsd">
    <ticket>
        <ticketId>0001</ticketId>
        <dateOfIssue>2021-02-06T22:20:30.087</dateOfIssue>
        <status>resolved</status>
        <userId>0002</userId>
        <subject>computer turns on and off randomly</subject>
        <description>computer will turn on and off randomly.</description>
        <supportMessages>
            <message time="2021-02-06T23:20:30.087">
                <userId>0001</userId>
                <content>Make sure the power cable is pushed in all the way</content>
            </message>
            <message time="2021-02-06T23:25:30.087">
                <userId>0002</userId>
                <content>Thank you, that fixed it</content>
            </message>
        </supportMessages>
    </ticket>
    <ticket>
        <ticketId>0002</ticketId>
        <dateOfIssue>2021-02-06T23:20:30.087</dateOfIssue>
        <status>open</status>
        <userId>0002</userId>
        <subject>can't access blackboard website</subject>
        <description>trying to open the blackboard website gives me and error saying that the site is not providing a valid certificate.</description>
    </ticket>
    <ticket>
        <ticketId>0003</ticketId>
        <dateOfIssue>2021-02-06T22:20:30.087</dateOfIssue>
        <status>on-going</status>
        <userId>0002</userId>
        <subject>No sound on blackboard</subject>
        <description>I don't get any sound when listening to lectures on blackboard</description>
        <supportMessages>
            <message time="2021-02-06T22:20:50.087">
                <userId>0001</userId>
                <content>Try unplugging and replugging your speakers / headphones</content>
            </message>
        </supportMessages>
    </ticket>
</tickets>

=== k4iru/School/HTTP-5203/HTTP5203-Assignment1-KyleCheung/tickets.xml
<?xml version="1.0" encoding="UTF-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets.xsd">
    <ticket>
        <ticketId>t0001</ticketId>
        <dateOfIssue>2021-02-06 22:20:30.087</dateOfIssue>
        <status>resolved</status>
        <userId>u0002</userId>
        <subject>computer turns on and off randomly</subject>
        <description>computer will turn on and off randomly.</description>
        <supportMessages>
            <message time="2021-02-06 23:20:30.087">
                <userId>u0001</userId>
                <content>Make sure the power cable is pushed in all the way</content>
            </message>
            <message time="2021-02-06 23:25:30.087">
                <userId>u0002</userId>
                <content>Thank you, that fixed it</content>
            </message>
        </supportMessages>
    </ticket>
    <ticket>
        <ticketId>t0002</ticketId>
        <dateOfIssue>2021-02-06 23:20:30.087</dateOfIssue>
        <status>open</status>
        <userId>u0002</userId>
        <subject>can't access blackboard website</subject>
        <description>trying to open the blackboard website gives me and error saying that the site is not providing a valid certificate.</description>
    </ticket>
    <ticket>
        <ticketId>t003</ticketId>
        <dateOfIssue>2021-02-06 22:20:30.087</dateOfIssue>
        <status>on-going</status>
        <userId>u0002</userId>
        <subject>No sound on blackboard</subject>
        <description>I don't get any sound when listening to lectures on blackboard</description>
        <supportMessages>
            <message time="2021-02-06 22:20:50.087">
                <userId>u0001</userId>
                <content>Try unplugging and replugging your speakers / headphones</content>
            </message>
        </supportMessages>
    </ticket>
</tickets>
