=== k4iru/School/HTTP-5203/assignment-2/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="userId" type="xs:integer" />
                            <xs:element name="userName" type="xs:string" />
                            <xs:element name="password" type="xs:string" />
                            <xs:element name="accountCreation" type="xs:dateTime" />
                            <xs:element name="userGroup">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="admin" />
                                        <xs:enumeration value="client" />
                                        <xs:enumeration value="support" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first" />
                                        <xs:element name="last" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== k4iru/School/HTTP-5203/HTTP5203-Assignment1-KyleCheung/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
    <user>
        <userId>u0001</userId>
        <userName>kcheu</userName>
        <password>9b8769a4a742959a2d0298c36fb70623f2dfacda8436237df08d8dfd5b37374c</password>
        <accountCreation>2021-02-06 22:07:31.713</accountCreation>
        <userGroup>admin</userGroup>
        <name>
            <first>kyle</first>
            <last>cheung</last>
        </name>
    </user>
    <user>
        <userId>u0002</userId>
        <userName>cli1</userName>
        <password>d258d3288a595e363c28ba7e62f2b33f734a64557016fa141fa04958f8b7543d</password>
        <accountCreation>2021-02-04 20:08:24.130</accountCreation>
        <userGroup>client</userGroup>
        <name>
            <first>john</first>
            <last>doe</last>
        </name>
    </user>
</users>

=== k4iru/School/HTTP-5203/assignment-2/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
    <user>
        <userId>0001</userId>
        <userName>kcheu</userName>
        <!-- password is "password" -->
        <password>5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8</password>
        <accountCreation>2021-02-06T22:07:31.713</accountCreation>
        <userGroup>admin</userGroup>
        <name>
            <first>kyle</first>
            <last>cheung</last>
        </name>
    </user>
    <user>
        <userId>0002</userId>
        <userName>cli1</userName>
        <!-- password is "client" -->
        <password>948fe603f61dc036b5c596dc09fe3ce3f3d30dc90f024c85f3c82db2ccab679d</password>
        <accountCreation>2021-02-04T20:08:24.130</accountCreation>
        <userGroup>client</userGroup>
        <name>
            <first>john</first>
            <last>doe</last>
        </name>
    </user>
</users>
